import os, textwrap, zipfile, pandas as pd, numpy as np, datetime as dt, json, re, pathlib, math
base = "/mnt/data/nova_retail_dashboard"
os.makedirs(base, exist_ok=True)

app_py = r'''"""
NovaRetail — Customer Intelligence Dashboard (Streamlit)

How to run (repo root must contain NR_dataset.xlsx):
  pip install -r requirements.txt
  streamlit run app.py

Key insights this app is designed to surface (will update dynamically with filters):
1) Revenue concentration: how much of revenue is generated by the top 10% customers (Pareto signal).
2) Segment performance: which behavioral segment (Promising/Growth/Stable/Decline) drives revenue and satisfaction.
3) Early warning: which customers show declining purchase frequency AND falling satisfaction (risk score).

Notes
- Offline-only: no external API calls.
- Single-file Streamlit app for easy grading/deployment.
- Dataset expected: NR_dataset.xlsx in repo root.
"""

from __future__ import annotations

import io
import math
from dataclasses import dataclass
from typing import Dict, List, Optional, Tuple

import numpy as np
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import plotly.io as pio
import streamlit as st


# -----------------------------
# Config
# -----------------------------
REQUIRED_COLS = [
    "CustomerID",
    "TransactionID",
    "TransactionDate",
    "ProductCategory",
    "PurchaseAmount",
    "CustomerAgeGroup",
    "CustomerGender",
    "CustomerRegion",
    "CustomerSatisfaction",
    "RetailChannel",
    "label",
]

SEGMENT_ORDER = ["Promising", "Growth", "Stable", "Decline"]

AGG_MAP = {"Daily": "D", "Monthly": "M", "Quarterly": "Q"}
APP_TITLE = "NovaRetail — Customer Intelligence Dashboard"


# -----------------------------
# Utilities
# -----------------------------
def _fmt_currency(x: float) -> str:
    try:
        return f"${x:,.0f}"
    except Exception:
        return str(x)


def _safe_str(x) -> str:
    if pd.isna(x):
        return ""
    return str(x)


def _minmax_01(s: pd.Series) -> pd.Series:
    """Min-max normalize to [0, 1]. If constant, return zeros."""
    s = s.astype(float)
    mn, mx = s.min(), s.max()
    if pd.isna(mn) or pd.isna(mx) or mx == mn:
        return pd.Series(np.zeros(len(s)), index=s.index)
    return (s - mn) / (mx - mn)


def _to_png_bytes(fig) -> bytes:
    """
    Export Plotly figure to PNG bytes (requires kaleido).
    Falls back to HTML bytes if PNG export fails.
    """
    try:
        return pio.to_image(fig, format="png", scale=2)
    except Exception:
        # Fallback: downloadable HTML snapshot (still useful offline)
        html = pio.to_html(fig, include_plotlyjs="cdn")
        return html.encode("utf-8")


# -----------------------------
# ETL / Feature engineering
# -----------------------------
@st.cache_data(show_spinner=False)
def load_data(path: str = "NR_dataset.xlsx") -> pd.DataFrame:
    """Read the Excel dataset and standardize types."""
    df = pd.read_excel(path, engine="openpyxl")
    # Keep only relevant columns (if extra columns exist)
    cols_present = [c for c in REQUIRED_COLS if c in df.columns]
    missing = [c for c in REQUIRED_COLS if c not in df.columns]
    if missing:
        raise ValueError(f"Missing required columns in Excel: {missing}")

    df = df[REQUIRED_COLS].copy()

    # Types
    df["CustomerID"] = df["CustomerID"].apply(_safe_str)
    df["TransactionID"] = df["TransactionID"].apply(_safe_str)

    # Dates
    df["TransactionDate"] = pd.to_datetime(df["TransactionDate"], errors="coerce")
    # Drop rows with invalid dates (cannot be analyzed in time-series)
    df = df.dropna(subset=["TransactionDate"]).copy()

    # Numeric sanitization
    df["PurchaseAmount"] = pd.to_numeric(df["PurchaseAmount"], errors="coerce").fillna(0.0)
    df["PurchaseAmount"] = df["PurchaseAmount"].clip(lower=0)

    df["CustomerSatisfaction"] = pd.to_numeric(df["CustomerSatisfaction"], errors="coerce")
    # Keep satisfaction in 1..5 if possible; otherwise NaN
    df.loc[~df["CustomerSatisfaction"].between(1, 5, inclusive="both"), "CustomerSatisfaction"] = np.nan

    # Categorical fill
    cat_cols = [
        "ProductCategory",
        "CustomerAgeGroup",
        "CustomerGender",
        "CustomerRegion",
        "RetailChannel",
        "label",
    ]
    for c in cat_cols:
        df[c] = df[c].astype("string").fillna("Unknown")

    # Derived: YearMonth (period) for stable grouping
    df["YearMonth"] = df["TransactionDate"].dt.to_period("M").astype(str)

    # Normalize label order (keep original text, but encourage canonical)
    df["label"] = df["label"].astype(str)
    return df


def add_customer_features(df: pd.DataFrame) -> pd.DataFrame:
    """
    Add per-customer features that are used across visuals:
    - CustomerLifetimeRevenue: sum PurchaseAmount per CustomerID (within current filtered window)
    - PurchaseFrequency: transaction count per customer (within current filtered window)
    - LastTransactionDate: most recent transaction date per customer
    """
    g = df.groupby("CustomerID", as_index=False)
    cust = g.agg(
        CustomerLifetimeRevenue=("PurchaseAmount", "sum"),
        PurchaseFrequency=("TransactionID", "nunique"),
        LastTransactionDate=("TransactionDate", "max"),
        Segment=("label", lambda s: s.iloc[-1]),
        Region=("CustomerRegion", lambda s: s.iloc[-1]),
        AvgSatisfaction=("CustomerSatisfaction", "mean"),
    )
    cust["LastTransactionDate"] = cust["LastTransactionDate"].dt.date.astype(str)
    return cust


def validate_data(df: pd.DataFrame) -> Dict[str, object]:
    """Basic validation summary shown at app start."""
    summary = {
        "rows": int(df.shape[0]),
        "cols": int(df.shape[1]),
        "customers": int(df["CustomerID"].nunique()),
        "date_min": str(df["TransactionDate"].min().date()),
        "date_max": str(df["TransactionDate"].max().date()),
        "missing_by_col": df.isna().sum().to_dict(),
        "purchase_amount_min": float(df["PurchaseAmount"].min()),
    }
    # Unit-test style asserts (kept in helper so app doesn't break silently)
    assert all(c in df.columns for c in REQUIRED_COLS), "Required columns missing after load."
    assert (df["PurchaseAmount"] >= 0).all(), "PurchaseAmount has negative values."
    assert df["CustomerID"].map(type).isin([str]).all(), "CustomerID should be string after conversion."
    return summary


# -----------------------------
# Filtering logic
# -----------------------------
@dataclass
class Filters:
    date_min: pd.Timestamp
    date_max: pd.Timestamp
    product_categories: List[str]
    regions: List[str]
    channels: List[str]
    segments: List[str]
    age_groups: List[str]
    genders: List[str]
    customer_id_search: str
    agg_level: str


def apply_filters(df: pd.DataFrame, f: Filters) -> pd.DataFrame:
    out = df.copy()
    out = out[(out["TransactionDate"] >= f.date_min) & (out["TransactionDate"] <= f.date_max)]
    if f.product_categories:
        out = out[out["ProductCategory"].isin(f.product_categories)]
    if f.regions:
        out = out[out["CustomerRegion"].isin(f.regions)]
    if f.channels:
        out = out[out["RetailChannel"].isin(f.channels)]
    if f.segments:
        out = out[out["label"].isin(f.segments)]
    if f.age_groups:
        out = out[out["CustomerAgeGroup"].isin(f.age_groups)]
    if f.genders:
        out = out[out["CustomerGender"].isin(f.genders)]
    if f.customer_id_search.strip():
        needle = f.customer_id_search.strip()
        out = out[out["CustomerID"].astype(str).str.contains(needle, case=False, na=False)]
    return out


# -----------------------------
# Metrics / Analytics
# -----------------------------
def compute_kpis(df_filt: pd.DataFrame, cust: pd.DataFrame) -> Dict[str, object]:
    total_rev = float(df_filt["PurchaseAmount"].sum())
    avg_purchase = float(df_filt["PurchaseAmount"].mean()) if len(df_filt) else 0.0
    n_customers = int(df_filt["CustomerID"].nunique())

    # Top segment by revenue
    seg_rev = (
        df_filt.groupby("label", as_index=False)["PurchaseAmount"].sum().sort_values("PurchaseAmount", ascending=False)
    )
    top_segment = seg_rev["label"].iloc[0] if len(seg_rev) else "—"

    # Revenue from top 10% customers (by lifetime revenue within window)
    if len(cust):
        cust_sorted = cust.sort_values("CustomerLifetimeRevenue", ascending=False).copy()
        top_n = max(1, int(math.ceil(0.10 * len(cust_sorted))))
        top10_rev = float(cust_sorted.head(top_n)["CustomerLifetimeRevenue"].sum())
    else:
        top10_rev = 0.0

    avg_sat = float(df_filt["CustomerSatisfaction"].mean()) if df_filt["CustomerSatisfaction"].notna().any() else np.nan

    return {
        "Total Revenue": total_rev,
        "Avg Purchase Amount": avg_purchase,
        "# Unique Customers": n_customers,
        "Top Segment by Revenue": top_segment,
        "Revenue from Top 10% Customers": top10_rev,
        "Avg Customer Satisfaction": avg_sat,
    }


def aggregate_timeseries(df_filt: pd.DataFrame, agg_level: str) -> pd.DataFrame:
    """Aggregate revenue over time by segment."""
    rule = AGG_MAP.get(agg_level, "M")
    ts = df_filt.copy()
    ts["bucket"] = ts["TransactionDate"].dt.to_period(rule).dt.to_timestamp()
    out = ts.groupby(["bucket", "label"], as_index=False).agg(Revenue=("PurchaseAmount", "sum"))
    out = out.sort_values("bucket")
    return out


def segment_health(df_filt: pd.DataFrame) -> pd.DataFrame:
    """Compute segment KPIs for tile/mini-charts."""
    g = df_filt.groupby("label", as_index=False).agg(
        Revenue=("PurchaseAmount", "sum"),
        AvgPurchase=("PurchaseAmount", "mean"),
        AvgSatisfaction=("CustomerSatisfaction", "mean"),
        Customers=("CustomerID", "nunique"),
    )
    total_rev = df_filt["PurchaseAmount"].sum()
    g["RevenueShare"] = np.where(total_rev > 0, g["Revenue"] / total_rev, 0.0)
    # Sort by canonical order when possible
    g["label"] = pd.Categorical(g["label"], categories=SEGMENT_ORDER, ordered=True)
    g = g.sort_values("label")
    g["label"] = g["label"].astype(str)
    return g


def pct_customers_declining_mom(df_filt: pd.DataFrame) -> float:
    """
    % customers declining month-over-month in revenue within filtered window:
    For each customer, compare last month revenue vs previous month revenue (in window).
    Declining if last < prev and both months exist.
    """
    if df_filt.empty:
        return 0.0

    tmp = df_filt.copy()
    tmp["ym"] = tmp["TransactionDate"].dt.to_period("M")
    months = sorted(tmp["ym"].unique())
    if len(months) < 2:
        return 0.0

    last_m, prev_m = months[-1], months[-2]
    by_c_m = tmp.groupby(["CustomerID", "ym"], as_index=False)["PurchaseAmount"].sum()
    pivot = by_c_m.pivot(index="CustomerID", columns="ym", values="PurchaseAmount").fillna(0.0)
    if prev_m not in pivot.columns or last_m not in pivot.columns:
        return 0.0
    declining = (pivot[last_m] < pivot[prev_m]) & (pivot[prev_m] > 0)
    denom = (pivot[prev_m] > 0).sum()
    if denom == 0:
        return 0.0
    return float(declining.sum() / denom)


def compute_risk_scores(df_filt: pd.DataFrame) -> pd.DataFrame:
    """
    Early warning risk score per customer over selected time window.

    risk_score = 0.6 * normalized_drop_in_purchase_frequency + 0.4 * normalized_drop_in_satisfaction

    - drop_in_purchase_frequency: compares tx count in last month vs previous month (within window)
    - drop_in_satisfaction: compares avg satisfaction in last month vs previous month (within window)
    Components are min-max normalized to [0, 1] across customers.
    """
    if df_filt.empty:
        return pd.DataFrame(columns=["CustomerID", "risk_score"])

    tmp = df_filt.copy()
    tmp["ym"] = tmp["TransactionDate"].dt.to_period("M")
    months = sorted(tmp["ym"].unique())
    if len(months) < 2:
        # Not enough months to compute a drop; return zeros
        base = tmp.groupby("CustomerID", as_index=False).agg(
            Segment=("label", lambda s: s.iloc[-1]),
            Region=("CustomerRegion", lambda s: s.iloc[-1]),
            LastTransactionDate=("TransactionDate", "max"),
        )
        base["risk_score"] = 0.0
        base["LastTransactionDate"] = base["LastTransactionDate"].dt.date.astype(str)
        return base.sort_values("risk_score", ascending=False)

    last_m, prev_m = months[-1], months[-2]

    # Purchase frequency per month (unique transactions)
    freq = tmp.groupby(["CustomerID", "ym"], as_index=False).agg(Tx=("TransactionID", "nunique"))
    freq_p = freq.pivot(index="CustomerID", columns="ym", values="Tx").fillna(0.0)
    prev_tx = freq_p[prev_m] if prev_m in freq_p.columns else pd.Series(0.0, index=freq_p.index)
    last_tx = freq_p[last_m] if last_m in freq_p.columns else pd.Series(0.0, index=freq_p.index)
    drop_freq = np.where(prev_tx > 0, (prev_tx - last_tx).clip(lower=0) / prev_tx, 0.0)

    # Satisfaction per month (avg)
    sat = tmp.groupby(["CustomerID", "ym"], as_index=False).agg(Sat=("CustomerSatisfaction", "mean"))
    sat_p = sat.pivot(index="CustomerID", columns="ym", values="Sat")
    prev_sat = sat_p.get(prev_m, pd.Series(np.nan, index=sat_p.index))
    last_sat = sat_p.get(last_m, pd.Series(np.nan, index=sat_p.index))
    sat_drop_raw = (prev_sat - last_sat)
    # convert to relative drop when prev exists and positive
    drop_sat = sat_drop_raw.fillna(0.0).clip(lower=0.0)

    # Normalize components to 0..1 across customers
    drop_freq_n = _minmax_01(pd.Series(drop_freq, index=freq_p.index))
    drop_sat_n = _minmax_01(pd.Series(drop_sat, index=sat_p.index))

    # Align indices
    ix = sorted(set(drop_freq_n.index).union(set(drop_sat_n.index)))
    drop_freq_n = drop_freq_n.reindex(ix).fillna(0.0)
    drop_sat_n = drop_sat_n.reindex(ix).fillna(0.0)

    risk = 0.6 * drop_freq_n + 0.4 * drop_sat_n

    base = tmp.groupby("CustomerID", as_index=False).agg(
        Segment=("label", lambda s: s.iloc[-1]),
        Region=("CustomerRegion", lambda s: s.iloc[-1]),
        LastTransactionDate=("TransactionDate", "max"),
        AvgSatisfaction=("CustomerSatisfaction", "mean"),
    )
    base["risk_score"] = base["CustomerID"].map(risk.to_dict()).fillna(0.0)
    base["LastTransactionDate"] = base["LastTransactionDate"].dt.date.astype(str)
    return base.sort_values("risk_score", ascending=False)


def what_if_lift(df_filt: pd.DataFrame, target_segment: str, retention_uplift_pct: float) -> Tuple[float, str]:
    """
    Conservative rule-based projection:
    - Compute average monthly revenue for target segment over the last 3 months in the selected window.
    - Project incremental revenue = avg_monthly_rev_last3 * 12 * (uplift_pct / 100) * 0.5
      The 0.5 is a conservative factor (assumes only half of uplift translates to retained revenue).
    """
    if df_filt.empty or retention_uplift_pct <= 0 or not target_segment:
        return 0.0, "No projection available."

    tmp = df_filt[df_filt["label"] == target_segment].copy()
    if tmp.empty:
        return 0.0, f"No data for segment '{target_segment}' in current filters."

    tmp["ym"] = tmp["TransactionDate"].dt.to_period("M").dt.to_timestamp()
    seg_m = tmp.groupby("ym", as_index=False).agg(Revenue=("PurchaseAmount", "sum")).sort_values("ym")
    last3 = seg_m.tail(3)
    if last3.empty:
        return 0.0, "Not enough history for projection."

    avg_monthly = float(last3["Revenue"].mean())
    lift = avg_monthly * 12.0 * (retention_uplift_pct / 100.0) * 0.5
    note = f"Based on avg monthly revenue over last {len(last3)} months in-window (conservative 50% translation)."
    return lift, note


# -----------------------------
# UI Components
# -----------------------------
def sidebar_filters(df: pd.DataFrame) -> Filters:
    st.sidebar.header("Filters")

    dmin, dmax = df["TransactionDate"].min(), df["TransactionDate"].max()
    date_range = st.sidebar.slider(
        "TransactionDate range",
        min_value=dmin.to_pydatetime(),
        max_value=dmax.to_pydatetime(),
        value=(dmin.to_pydatetime(), dmax.to_pydatetime()),
    )

    # Multiselects
    product_categories = st.sidebar.multiselect(
        "ProductCategory",
        options=sorted(df["ProductCategory"].unique().tolist()),
        default=sorted(df["ProductCategory"].unique().tolist()),
    )
    regions = st.sidebar.multiselect(
        "CustomerRegion",
        options=sorted(df["CustomerRegion"].unique().tolist()),
        default=sorted(df["CustomerRegion"].unique().tolist()),
    )
    channels = st.sidebar.multiselect(
        "RetailChannel",
        options=sorted(df["RetailChannel"].unique().tolist()),
        default=sorted(df["RetailChannel"].unique().tolist()),
    )
    segments = st.sidebar.multiselect(
        "Segment (label)",
        options=sorted(df["label"].unique().tolist()),
        default=sorted(df["label"].unique().tolist()),
    )
    age_groups = st.sidebar.multiselect(
        "CustomerAgeGroup",
        options=sorted(df["CustomerAgeGroup"].unique().tolist()),
        default=sorted(df["CustomerAgeGroup"].unique().tolist()),
    )
    genders = st.sidebar.multiselect(
        "CustomerGender",
        options=sorted(df["CustomerGender"].unique().tolist()),
        default=sorted(df["CustomerGender"].unique().tolist()),
    )

    agg_level = st.sidebar.radio("Aggregation level", ["Daily", "Monthly", "Quarterly"], index=1)

    customer_id_search = st.sidebar.text_input("Search CustomerID (contains)", value="")

    return Filters(
        date_min=pd.Timestamp(date_range[0]),
        date_max=pd.Timestamp(date_range[1]),
        product_categories=product_categories,
        regions=regions,
        channels=channels,
        segments=segments,
        age_groups=age_groups,
        genders=genders,
        customer_id_search=customer_id_search,
        agg_level=agg_level,
    )


def kpi_row(kpis: Dict[str, object]) -> None:
    c1, c2, c3, c4, c5, c6 = st.columns(6)
    c1.metric("Total Revenue", _fmt_currency(kpis["Total Revenue"]))
    c2.metric("Avg Purchase", _fmt_currency(kpis["Avg Purchase Amount"]))
    c3.metric("# Unique Customers", f"{kpis['# Unique Customers']:,}")
    c4.metric("Top Segment (Revenue)", str(kpis["Top Segment by Revenue"]))
    c5.metric("Revenue from Top 10%", _fmt_currency(kpis["Revenue from Top 10% Customers"]))
    sat = kpis["Avg Customer Satisfaction"]
    c6.metric("Avg Satisfaction", "—" if pd.isna(sat) else f"{sat:.2f}")


def chart_revenue_trend(ts: pd.DataFrame) -> go.Figure:
    fig = px.line(
        ts,
        x="bucket",
        y="Revenue",
        color="label",
        markers=True,
        category_orders={"label": SEGMENT_ORDER},
        labels={"bucket": "Date", "Revenue": "Revenue", "label": "Segment"},
        title="Revenue Trend by Segment",
    )
    fig.update_layout(legend_title_text="Segment", hovermode="x unified")
    fig.update_yaxes(tickprefix="$", separatethousands=True)
    return fig


def chart_rev_by_category(df_filt: pd.DataFrame) -> go.Figure:
    agg = df_filt.groupby(["ProductCategory", "label"], as_index=False)["PurchaseAmount"].sum()
    fig = px.bar(
        agg,
        x="ProductCategory",
        y="PurchaseAmount",
        color="label",
        barmode="stack",
        category_orders={"label": SEGMENT_ORDER},
        labels={"PurchaseAmount": "Revenue", "label": "Segment"},
        title="Revenue by Product Category (stacked by segment)",
    )
    fig.update_yaxes(tickprefix="$", separatethousands=True)
    return fig


def chart_rev_by_region(df_filt: pd.DataFrame) -> go.Figure:
    agg = df_filt.groupby("CustomerRegion", as_index=False)["PurchaseAmount"].sum().sort_values("PurchaseAmount", ascending=False)
    fig = px.bar(
        agg,
        x="CustomerRegion",
        y="PurchaseAmount",
        labels={"PurchaseAmount": "Revenue", "CustomerRegion": "Region"},
        title="Revenue by Region",
    )
    fig.update_yaxes(tickprefix="$", separatethousands=True)
    return fig


def segment_health_tiles(health: pd.DataFrame, pct_declining: float) -> None:
    st.subheader("Segment Health")
    st.caption("Tiles update with filters. Use them to spot segments that are high revenue but slipping satisfaction.")
    cols = st.columns(4)
    for i, seg in enumerate(SEGMENT_ORDER):
        seg_row = health[health["label"] == seg]
        if seg_row.empty:
            cols[i].metric(seg, "—")
            continue
        r = seg_row.iloc[0]
        cols[i].metric(
            seg,
            _fmt_currency(r["Revenue"]),
            help=f"Revenue share: {r['RevenueShare']*100:.1f}% | Avg purchase: ${r['AvgPurchase']:.0f} | Avg satisfaction: {r['AvgSatisfaction']:.2f}",
        )

    st.caption(f"% customers declining month-over-month (in-window): **{pct_declining*100:.1f}%**")


def top_customers_table(cust: pd.DataFrame, top_n: int = 15) -> None:
    st.subheader("Top Customers by Lifetime Revenue (in-window)")
    st.caption("Use this to focus retention / VIP programs and understand revenue concentration.")
    show = cust.sort_values("CustomerLifetimeRevenue", ascending=False).head(top_n).copy()
    show.rename(
        columns={
            "CustomerLifetimeRevenue": "LifetimeRevenue",
            "AvgSatisfaction": "Satisfaction",
        },
        inplace=True,
    )
    show["LifetimeRevenue"] = show["LifetimeRevenue"].round(2)
    show["Satisfaction"] = show["Satisfaction"].round(2)

    st.dataframe(
        show[
            ["CustomerID", "LifetimeRevenue", "PurchaseFrequency", "LastTransactionDate", "Segment", "Region", "Satisfaction"]
        ],
        use_container_width=True,
        hide_index=True,
    )

    csv = show.to_csv(index=False).encode("utf-8")
    st.download_button("Download top customers CSV", csv, "top_customers.csv", "text/csv")


def risk_section(risk: pd.DataFrame, df_filt: pd.DataFrame) -> None:
    st.subheader("Early Warning: At-Risk Customers")
    with st.popover("How the risk score works"):
        st.markdown(
            """
**Risk score** flags customers with **declining purchase frequency** and **falling satisfaction** in the selected time window.

Formula (normalized to 0–1 per customer):
`risk_score = 0.6 * normalized_drop_in_purchase_frequency + 0.4 * normalized_drop_in_satisfaction`

- Drop in purchase frequency: compares **last month vs previous month** transaction counts.
- Drop in satisfaction: compares **last month vs previous month** average satisfaction.
- Higher risk score = more at-risk.
"""
        )

    top = risk.head(10).copy()
    top["risk_score"] = top["risk_score"].round(3)
    st.dataframe(
        top[["CustomerID", "risk_score", "Segment", "Region", "LastTransactionDate", "AvgSatisfaction"]],
        use_container_width=True,
        hide_index=True,
    )

    # Visual: risk distribution by segment
    if not risk.empty:
        fig = px.box(
            risk,
            x="Segment",
            y="risk_score",
            points="all",
            category_orders={"Segment": SEGMENT_ORDER},
            labels={"risk_score": "Risk score"},
            title="Risk Score Distribution by Segment",
        )
        st.plotly_chart(fig, use_container_width=True)
        png = _to_png_bytes(fig)
        st.download_button("Download chart snapshot (PNG/HTML)", png, "risk_chart.png", "image/png")


def what_if_section(df_filt: pd.DataFrame) -> None:
    st.subheader("What-If / Investment Lens (Retention)")
    st.caption("Simple, conservative projection to support prioritization discussions (not a predictive model).")

    segs = sorted(df_filt["label"].unique().tolist()) if not df_filt.empty else SEGMENT_ORDER
    target = st.selectbox("Target segment", options=segs, index=0 if segs else 0)
    uplift = st.slider("Retention uplift (%)", min_value=0, max_value=20, value=5, step=1)

    lift, note = what_if_lift(df_filt, target, float(uplift))

    c1, c2 = st.columns([1, 2])
    c1.metric("Estimated incremental revenue (12 mo)", _fmt_currency(lift))
    c2.info(note)

    # Visual: show base vs lift bar
    base = float(df_filt[df_filt["label"] == target]["PurchaseAmount"].sum()) if not df_filt.empty else 0.0
    fig = go.Figure(
        data=[
            go.Bar(name="Observed revenue (in-window)", x=["Revenue"], y=[base]),
            go.Bar(name=f"Estimated lift (+{uplift}%)", x=["Revenue"], y=[lift]),
        ]
    )
    fig.update_layout(barmode="group", title="Observed vs Estimated Lift", yaxis_title="Revenue")
    fig.update_yaxes(tickprefix="$", separatethousands=True)
    st.plotly_chart(fig, use_container_width=True)
    png = _to_png_bytes(fig)
    st.download_button("Download chart snapshot (PNG/HTML)", png, "what_if.png", "image/png")


# -----------------------------
# Main App
# -----------------------------
def main() -> None:
    st.set_page_config(page_title=APP_TITLE, layout="wide")
    st.title(APP_TITLE)
    st.caption("Interactive exploration of customer segments, revenue patterns, and early warning indicators.")

    with st.expander("How to use"):
        st.markdown(
            """
1. Use the **sidebar filters** to slice by date range, category, region, channel, segment, and demographics.
2. Start at the **KPIs** to understand the current slice (revenue, customers, top segment, concentration).
3. Use **Revenue Trend** and **Category/Region** charts to identify growth opportunities.
4. Check **Segment Health** and **At-Risk Customers** for early warning indicators.
5. Use **What-If** to size the potential lift of improving retention in a target segment.
"""
        )

    # Load + validate
    try:
        df = load_data("NR_dataset.xlsx")
    except Exception as e:
        st.error(
            "Could not load NR_dataset.xlsx from the repo root. "
            "Make sure NR_dataset.xlsx is next to app.py in your GitHub repo."
        )
        st.exception(e)
        st.stop()

    summary = validate_data(df)

    # Data summary / validation section (executed on app start)
    with st.expander("Dataset validation summary (auto)"):
        st.write(
            {
                "rows": summary["rows"],
                "cols": summary["cols"],
                "unique_customers": summary["customers"],
                "date_min": summary["date_min"],
                "date_max": summary["date_max"],
                "purchase_amount_min": summary["purchase_amount_min"],
            }
        )
        st.write("Missing values by column:")
        st.dataframe(pd.DataFrame({"missing": summary["missing_by_col"]}).T, use_container_width=True)

    # Sidebar filters
    f = sidebar_filters(df)
    df_filt = apply_filters(df, f)

    # Derived customer features (in-window)
    cust = add_customer_features(df_filt)

    # KPIs
    kpis = compute_kpis(df_filt, cust)
    kpi_row(kpis)

    if df_filt.empty:
        st.warning("No data matches the current filters. Adjust filters to see charts.")
        st.stop()

    # Layout: charts
    left, right = st.columns([2, 1])

    with left:
        ts = aggregate_timeseries(df_filt, f.agg_level)
        fig_ts = chart_revenue_trend(ts)
        st.plotly_chart(fig_ts, use_container_width=True)
        png = _to_png_bytes(fig_ts)
        st.download_button("Download chart snapshot (PNG/HTML)", png, "revenue_trend.png", "image/png")

    with right:
        fig_cat = chart_rev_by_category(df_filt)
        st.plotly_chart(fig_cat, use_container_width=True)
        png = _to_png_bytes(fig_cat)
        st.download_button("Download chart snapshot (PNG/HTML)", png, "revenue_by_category.png", "image/png")

    fig_reg = chart_rev_by_region(df_filt)
    st.plotly_chart(fig_reg, use_container_width=True)
    png = _to_png_bytes(fig_reg)
    st.download_button("Download chart snapshot (PNG/HTML)", png, "revenue_by_region.png", "image/png")

    # Segment health
    health = segment_health(df_filt)
    pct_decl = pct_customers_declining_mom(df_filt)
    segment_health_tiles(health, pct_decl)

    # Top customers
    top_n = st.slider("Top N customers", min_value=5, max_value=50, value=15, step=5)
    top_customers_table(cust, top_n=top_n)

    # Risk / early warning
    risk = compute_risk_scores(df_filt)
    risk_section(risk, df_filt)

    # What-if
    what_if_section(df_filt)

    # Footer note on cross-filtering
    st.caption(
        "Tip: Streamlit filtering is controlled via the sidebar. "
        "Charts are interactive (hover, zoom, legend toggles). "
        "For strict cross-filtering across components, apply equivalent sidebar filters."
    )


if __name__ == "__main__":
    main()
'''
